# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ecb6dd0dc145b876a2950abd309ae9be35f8027e69ffd32b9e0a685bf0800dd14e89398f587e9abb49b48ff31e70a12d8a4f8013bb7b672ff5851a3dfd9b5e7

test:
  secret_key_base: 8e5539c65b20946b8c5a6b73be0be08782b312992b5f593d87b2a6e9023bf67fca98ebf904b539e6cdd32d515a0b1f3a50ce07809271e9ad8869c173801649b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
